name: Scala CI

on:
  push:
    branches: [ "main", "master", "development" ]
  pull_request:
    branches: [ "main", "master", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'

    # DAS HIER IST NEU: Installiert das sbt-Kommando
    - name: Setup sbt
      uses: sbt/setup-sbt@v1

    - name: Run Tests and generate Coverage
      run: sbt clean coverage test coverageReport

    - name: Upload Coverage to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt coveralls

    - name: Run Mutation Tests (Stryker4s)
      run: sbt stryker